name: Action

on:
  push:
    branches:
      - master

jobs:
  generateClient:
    name: Generate Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout current client
        uses: actions/checkout@v4
        with:
          repository: InternalErrorGit/spring-testing-client
          path: spring-testing-client
      - name: Generate new Client
        run: mvn --batch-mode install
      - name: Push new Client
        run: |
          cd spring-testing-client
          git config --global user.name "InternalErrorGit"
          git config --global user.email "phil.gatzka@gmail.com"
          git commit -am "Published new Version"
          git push