name: Action

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  generateClient:
    name: Generate Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout current client
        uses: actions/checkout@v4
        with:
          repository: InternalErrorGit/spring-testing-client
          path: spring-testing-client
      - name: Generate new Client
        run: mvn --batch-mode install
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: 'spring-testing-client'
          destination-github-username: 'InternalErrorGit'
          destination-repository-name: 'spring-testing-client'
          user-email: carles3@pina.cat
          commit-message: "Pushing client updates"